#!/bin/bash
# Setup script for automated Docker cleanup cron job
# This script installs the docker-cleanup.sh as a weekly cron job
#
# Usage:
#   sudo ./setup-cron-cleanup.sh [PROJECT_PATH]
#
# Example:
#   sudo ./setup-cron-cleanup.sh /opt/translate-java-property-files
#
# What this script does:
#   1. Copies docker-cleanup.sh to the project directory
#   2. Makes it executable
#   3. Creates a weekly cron job in /etc/cron.weekly/
#   4. Tests the cleanup script
#
# Requirements:
#   - Must be run as root (for cron installation)
#   - Docker must be installed
#   - Project path must exist

set -e

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Error: This script must be run as root (use sudo)"
    exit 1
fi

# Get project path from argument or use current directory
PROJECT_PATH="${1:-$(pwd)}"

if [ ! -d "$PROJECT_PATH" ]; then
    echo "Error: Project path does not exist: $PROJECT_PATH"
    exit 1
fi

echo "Setting up automated Docker cleanup for: $PROJECT_PATH"

# Copy cleanup script to project directory
SCRIPT_SOURCE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/docker-cleanup.sh"
SCRIPT_DEST="$PROJECT_PATH/docker-cleanup.sh"

echo "Copying cleanup script to $SCRIPT_DEST"
cp "$SCRIPT_SOURCE" "$SCRIPT_DEST"
chmod +x "$SCRIPT_DEST"

# Create cron job
# Sanitize project name for safe filename usage
PROJECT_NAME=$(basename "$PROJECT_PATH" | sed 's/[^a-zA-Z0-9._-]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//')
CRON_FILE="/etc/cron.weekly/docker-cleanup-${PROJECT_NAME}"

echo "Creating weekly cron job: $CRON_FILE"
cat > "$CRON_FILE" << EOF
#!/bin/bash
# Weekly Docker cleanup for ${PROJECT_NAME}
# Auto-generated by setup-cron-cleanup.sh

cd "${PROJECT_PATH}" && ./docker-cleanup.sh
EOF

chmod +x "$CRON_FILE"

# Test the cleanup script
echo "Testing cleanup script..."
cd "$PROJECT_PATH" && ./docker-cleanup.sh

echo ""
echo "✅ Setup complete!"
echo ""
echo "Installed:"
echo "  - Cleanup script: $SCRIPT_DEST"
echo "  - Cron job: $CRON_FILE (runs weekly)"
echo ""
echo "Verify installation:"
echo "  - Check cron job: ls -lh $CRON_FILE"
echo "  - View logs: tail -50 $PROJECT_PATH/logs/docker-cleanup.log"
echo "  - Test manually: cd $PROJECT_PATH && ./docker-cleanup.sh"
